# .goreleaser.yaml
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/prusa-link-mqtt-bridge
    binary: prusa-link-mqtt-bridge
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:{{ .Version }}-{{ .Runtime.Goos }}-{{ .Runtime.Goarch }}"
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:{{ .Major }}-{{ .Runtime.Goos }}-{{ .Runtime.Goarch }}"
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:{{ .Major }}.{{ .Minor }}-{{ .Runtime.Goos }}-{{ .Runtime.Goarch }}"
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:latest"
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:{{ .Version }}-{{ .Runtime.Goos }}-{{ .Runtime.Goarch }}"
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:{{ .Major }}-{{ .Runtime.Goos }}-{{ .Runtime.Goarch }}"
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:{{ .Major }}.{{ .Minor }}-{{ .Runtime.Goos }}-{{ .Runtime.Goarch }}"
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:latest"
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx

release:
  name_template: "{{ .Tag }}"
  draft: false
  prerelease: auto

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
