# .goreleaser.yaml

version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/prusa-link-mqtt-bridge
    binary: prusa-link-mqtt-bridge
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:{{ .Tag }}-amd64"
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:latest-amd64"
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:{{ .Tag }}-arm64"
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:latest-arm64"
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/floschl8/prusa-link-mqtt-bridge:{{ .Tag }}"
    image_templates:
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:{{ .Tag }}-arm64"
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:{{ .Tag }}-amd64"
  - name_template: "ghcr.io/floschl8/prusa-link-mqtt-bridge:latest"
    image_templates:
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:latest-arm64"
      - "ghcr.io/floschl8/prusa-link-mqtt-bridge:latest-amd64"

release:
  name_template: "{{ .Tag }}"
  draft: false
  prerelease: auto

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
