name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write # For status checks

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Go Fmt
        run: go fmt ./...

      - name: Go Vet
        run: go vet ./...

      - name: Run Tests and Generate Coverage
        run: go test -v -coverprofile=coverage.out ./...

